openapi: 3.1.0
info:
  title: Schnittstellen des Lieferanten Backends für MaloIdent Lösung
  description: |
    Folgende Schnittstellen muss das Backend des Lieferanten bereitstellen um die MaloIdent Antwort empfangen zu können

    <details>
    <summary>Changelog</summary>
    -
       
    **Version 1.0.4** - *13. Januar 2025* - _Autor: Tu Quy Nguyen_
      - Added security schema for the API and fixed date format in the schema 

    **Version 1.0.3** - *17. Dezember 2024* - _Autor: DAS_
      - Rollencodetyp bei Absender und Emfpfaenger entfernt

    **Version 1.0.2** - *10. Dezember 2024* - _Autor: DAS_
      - Aktualisierung der zusatzdaten
    
    **Version 1.0.1** - *02. Dezember 2024* - _Autor: DAS_

    - Ergänzung  `ERSTELLEN_PROZESSDATEN_MALOIDENTANTWORT_NEGATIV`-Schema.

    **Version 1.0.0** - *01. November 2024* - _Autor: DAS_

    - Initiale Veröffentlichung der Doku mit dem `ERSTELLEN_PROZESSDATEN_MALOIDENTANTWORT_POSITIV`-Schema.

    </details>
  version: 1.0.3
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

externalDocs:
  description: "MaloIdent Dokumentation"
  url: "https://doku.macoapp.conuti.de/maloIdent"  

servers:
  - url: https://demoapi.macoapp.de
    description: Beispiel URL (Test- und produktive URL weichen ab)
tags:
  - name: POSITIV
    description: Schnittstellen die das Backend des Lieferanten für den Empfang der positiven Marktantwort bereitstellen muss     
  - name: NEGATIV
    description: Schnittstellen die das Backend des Lieferanten für den Empfang der negativen Marktantwort bereitstellen muss      
security: []
paths:
  $ref: paths/_index.yml