openapi: 3.1.0
info:
  title: Schnittstellen der MaloIdent Lösung
  description: |
    Folgende Schnittstellen bietet die MaloIdent Lösung für die Anbindung an ein Backendsystem.  

    <details>
    <summary>Changelog</summary>   
    -
       
    **Version 1.0.5** - *13. Januar 2025* - _Autor: Tu Quy Nguyen_
      - Added security schema for the API and fixed date format in the schema 
    
    **Version 1.0.4** - *07. Januar 2025* - _Autor: DAS_
      - Falsches `data` Root Element entfernt

    **Version 1.0.3** - *17. Dezember 2024* - _Autor: DAS_
      - Rollencodetyp bei Absender und Emfpfaenger entfernt

    **Version 1.0.2** - *09. Dezember 2024* - _Autor: DAS_
      - Aktualisierung des Event Schema in Bezug auf Zeitscheibenbehandlung
    
    **Version 1.0.1** - *02. Dezember 2024* - _Autor: DAS_

    - Aktualisierung des Event Schema - Entferung Netznutzungsvertrag

    **Version 1.0.0** - *01. November 2024* - _Autor: DAS_

    - Initiale Veröffentlichung der Doku mit dem `START_MALOIDENT`-Schema.

    </details>
  version: 1.0.4
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

externalDocs:
  description: "MaloIdent Dokumentation"
  url: "https://doku.macoapp.conuti.de/maloIdent"  

servers:
  - url: https://demoapi.macoapp.de
    description: Beispiel URL (Test- und produktive URL weichen ab)
tags:
  - name: LIEFERANT
    description: Schnittstellen der MaloIdent Lösung für die Rolle Lieferant         
security: []
paths:
  $ref: paths/_index.yml