openapi: 3.1.0
info:
  title: Schnittstellen der MACO APP
  description: |
    Folgende Schnittstellen bietet die MACO APP einem Backend für das Auslösen von Prozessen.  

    <details>
    <summary>Changelog</summary>
    
    - **Version 1.0.2** - *04. Oktober 2024* - _Autor: DAS_
      - Update START_LIEFERBEGINN und START_LIEFERENDE
    
    **Version 1.0.1** - *08. August 2024* - _Autor: DAS_

    - Erweiterung der API um zusätzliche Schemas und Beispiele.
    - Hinzugefügte Schemas: `START_LIEFERBEGINN_STROM`, `START_LIEFERBEGINN_GAS`, `START_ABR_NN`, `START_DEFINITION_SCHALTZEIT`, `START_DEFINITION_LEISTUNGSKURVE`, `START_DEFINITION_ZAEHLZEIT`, `START_KUENDIGUNG`.

    **Version 1.0.0** - *01. August 2024* - _Autor: DAS_

    - Initiale Veröffentlichung der API mit dem `START_SPERRAUFTRAG`-Schema.

    </details>
  version: 1.0.2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://api.macoapp.de
    description: Fake Env
tags:
  - name: TRIGGER
    description: Trigger Events aus dem Backend       
paths:
  $ref: paths/_index.yml